export { default as AdminLogin } from "./admin_login";
export * from "./admin_login";
export { default as LabConsole } from "./lab_console";
export * from "./lab_console";
export { default as LabDetails } from "./lab_details";
export * from "./lab_details";
export { default as StaffConsole } from "./staff_console";
export * from "./staff_console";
export { default as CustomerConsole } from "./customer_console";
export * from "./customer_console";
export { default as ServicesConsole } from "./services_console";
export * from "./services_console";
export { default as PackagesConsole } from "./packages_console";
export * from "./packages_console";
export { PayrollConsole } from "./payroll_console";
export * from "./payroll_console";
